name: jgms_mobile
description: A new Flutter project for JGMS mobile app with secure authentication.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3

  # Networking
  dio: ^5.7.0

  # Secure Storage & Biometrics
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0

  # Helper icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
